CREATE TABLE IF NOT EXISTS `singer` (
  `id`   INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50),
  PRIMARY KEY (`id`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



CREATE TABLE IF NOT EXISTS `song` (
  `id`          INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `title`       VARCHAR(50),
  `lyric`       TEXT DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE(`title`, `lyric`)
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;



CREATE TABLE IF NOT EXISTS `singer_song` (
  `singer_id` INT(10) UNSIGNED NOT NULL,
  `song_id`   INT(10) UNSIGNED NOT NULL,
  `mp3path`   VARCHAR(200) DEFAULT NULL,
  UNIQUE(`singer_id`,`song_id`, `mp3path`),
  CONSTRAINT `fk_singer` FOREIGN KEY (`singer_id`) REFERENCES `singer` (`id`)
  ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `fk_song` FOREIGN KEY (`song_id`) REFERENCES `song` (`id`)
  ON DELETE NO ACTION ON UPDATE CASCADE
)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
